"""Added admin table

Revision ID: 42661ffaebd0
Revises: 8aa0512d051d
Create Date: 2023-03-31 17:09:26.434824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42661ffaebd0'
down_revision = '8aa0512d051d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
